/// <reference types="mocha" />
/// <reference types="chai" />
/// <reference types="sinon" />
/// <reference types="sinon-chai" />
declare var sinon: sinon.SinonStatic
declare var describe: Mocha.IContextDefinition
declare var xdescribe: Mocha.IContextDefinition
declare var it: Mocha.ITestDefinition
declare var xit: Mocha.ITestDefinition
declare var expect: Chai.ExpectStatic
